<?php

namespace Database\Seeders;

use App\Models\Page;
use Illuminate\Database\Seeder;

class AboutPageSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $aboutSections = [
            'section_order' => [
                'hero' => ['sort_order' => 1, 'enabled' => true],
                'story' => ['sort_order' => 2, 'enabled' => true],
                'services' => ['sort_order' => 3, 'enabled' => true],
                'why_choose' => ['sort_order' => 4, 'enabled' => true],
                'how_it_works' => ['sort_order' => 5, 'enabled' => true],
                'mission' => ['sort_order' => 6, 'enabled' => true],
                'cta' => ['sort_order' => 7, 'enabled' => true],
            ],
            'hero' => [
                'enabled' => true,
                'eyebrow_ar' => 'من نحن',
                'eyebrow_en' => 'About Us',
                'title_ar' => 'من نحن',
                'title_en' => 'About Travel Wave',
                'subtitle_ar' => 'في Travel Wave بنساعدك تخطط لرحلتك بثقة، ونوفر لك خدمات السفر والتأشيرات من أول خطوة حتى الاستعداد للسفر.',
                'subtitle_en' => 'We help you plan your journey with confidence, providing professional travel and visa services from the first step until you are ready to travel.',
            ],
            'story' => [
                'enabled' => true,
                'eyebrow_ar' => 'نبذة عنا',
                'eyebrow_en' => 'Who We Are',
                'title_ar' => 'من نحن؟',
                'title_en' => 'Who We Are',
                'description_ar' => "Travel Wave شركة متخصصة في خدمات السفر والسياحة والتأشيرات، بنساعد عملاءنا على التخطيط لرحلاتهم وإنهاء الإجراءات المرتبطة بالسفر بطريقة منظمة واحترافية.\n\nبنقدم مجموعة متكاملة من خدمات السفر، تشمل خدمات التأشيرات، تجهيز ملفات التقديم، حجز مواعيد السفارات ومراكز التأشيرات، حجوزات الطيران والفنادق، بالإضافة إلى الرحلات السياحية الداخلية والخارجية.\n\nهدفنا هو تبسيط خطوات السفر وتوفير الدعم المناسب لكل عميل بناءً على وجهته واحتياجاته.\n\nنؤمن إن رحلة العميل بتبدأ قبل السفر بوقت طويل، وعشان كده بنهتم إن مرحلة التخطيط والتجهيز تكون أوضح وأسهل وأكثر تنظيمًا.",
                'description_en' => "Travel Wave is a specialized travel, tourism, and visa services agency. We help our clients plan their trips and complete all travel-related procedures in an organized and professional manner.\n\nWe provide a comprehensive range of services including visa assistance, application file preparation, embassy appointment scheduling, flight and hotel bookings, as well as domestic and international tour packages.\n\nOur goal is to simplify travel steps and provide tailored support for every client based on their destination and requirements.",
                'points' => [
                    ['text_ar' => 'حلول متكاملة تبدأ من أول استفسار وحتى الجاهزية التامة للسفر.', 'text_en' => 'Integrated solutions from first inquiry until full travel readiness.', 'is_active' => true, 'sort_order' => 1],
                    ['text_ar' => 'تخفيف تعقيدات الإجراءات وإعادة ترتيب الخطوات بأسلوب سهل وواضح.', 'text_en' => 'Simplifying complex procedures into clear, step-by-step guidance.', 'is_active' => true, 'sort_order' => 2],
                    ['text_ar' => 'متابعة دقيقة للتفاصيل لضمان تجربة سفر مريحة وبأعلى مستوى من التنظيم.', 'text_en' => 'Meticulous attention to detail ensuring an organized travel experience.', 'is_active' => true, 'sort_order' => 3],
                ],
            ],
            'services' => [
                'enabled' => true,
                'eyebrow_ar' => 'خدماتنا الشاملة',
                'eyebrow_en' => 'Our Services',
                'title_ar' => 'خدماتنا',
                'title_en' => 'Our Services',
                'subtitle_ar' => 'حلول متكاملة تساعدك تجعل تجربة السفر أسهل وأكثر تنظيمًا.',
                'subtitle_en' => 'Integrated solutions designed to make your travel experience easier and more organized.',
                'items' => [
                    [
                        'icon' => 'VS',
                        'title_ar' => 'التأشيرات الخارجية',
                        'title_en' => 'External Visas',
                        'text_ar' => 'نساعدك في تجهيز ملف التأشيرة وفهم المتطلبات والإجراءات اللازمة حسب الدولة والوجهة.',
                        'text_en' => 'Guidance in preparing your visa application file and understanding country requirements.',
                        'is_active' => true,
                        'sort_order' => 1,
                    ],
                    [
                        'icon' => 'FL',
                        'title_ar' => 'حجز تذاكر الطيران',
                        'title_en' => 'Flight Bookings',
                        'text_ar' => 'نساعدك في اختيار وحجز رحلات الطيران المناسبة لوجهتك وموعد سفرك.',
                        'text_en' => 'Helping you select and book suitable flights tailored to your schedule.',
                        'is_active' => true,
                        'sort_order' => 2,
                    ],
                    [
                        'icon' => 'HT',
                        'title_ar' => 'حجز الفنادق',
                        'title_en' => 'Hotel Bookings',
                        'text_ar' => 'نوفر لك خيارات حجز فنادق مناسبة لوجهتك واحتياجات رحلتك.',
                        'text_en' => 'Providing flexible hotel reservation options matching your travel needs.',
                        'is_active' => true,
                        'sort_order' => 3,
                    ],
                    [
                        'icon' => 'DT',
                        'title_ar' => 'الرحلات والباقات السياحية',
                        'title_en' => 'Tour Packages',
                        'text_ar' => 'باقات ورحلات سياحية داخلية وخارجية تناسب مختلف احتياجات المسافرين.',
                        'text_en' => 'Domestic and international tour packages customized for all traveler preferences.',
                        'is_active' => true,
                        'sort_order' => 4,
                    ],
                    [
                        'icon' => 'FO',
                        'title_ar' => 'تجهيز ملفات التأشيرات',
                        'title_en' => 'Visa File Preparation',
                        'text_ar' => 'مساعدة في تنظيم وتجهيز المستندات المطلوبة للتقديم وفقًا لمتطلبات الخدمة والوجهة.',
                        'text_en' => 'Professional organization and preparation of all required application documents.',
                        'is_active' => true,
                        'sort_order' => 5,
                    ],
                    [
                        'icon' => 'BO',
                        'title_ar' => 'حجز مواعيد السفارات ومراكز التأشيرات',
                        'title_en' => 'Embassy Appointment Booking',
                        'text_ar' => 'المساعدة في إجراءات حجز المواعيد حسب المتاح ومتطلبات جهة التقديم.',
                        'text_en' => 'Assistance in scheduling embassy and visa processing center appointments.',
                        'is_active' => true,
                        'sort_order' => 6,
                    ],
                    [
                        'icon' => 'SP',
                        'title_ar' => 'الترجمة المعتمدة',
                        'title_en' => 'Certified Translation',
                        'text_ar' => 'خدمات ترجمة معتمدة للمستندات المطلوبة ضمن إجراءات السفر والتأشيرات.',
                        'text_en' => 'Certified translation services for all required visa and travel documents.',
                        'is_active' => true,
                        'sort_order' => 7,
                    ],
                ],
            ],
            'why_choose' => [
                'enabled' => true,
                'eyebrow_ar' => 'لماذا نحن',
                'eyebrow_en' => 'Why Choose Us',
                'title_ar' => 'ليه تختار Travel Wave؟',
                'title_en' => 'Why Choose Travel Wave?',
                'items' => [
                    [
                        'icon' => 'EX',
                        'title_ar' => 'خبرة في خدمات السفر والتأشيرات',
                        'title_en' => 'Travel & Visa Expertise',
                        'text_ar' => 'فهم أفضل لمتطلبات السفر وإجراءات التأشيرات المختلفة.',
                        'text_en' => 'A strong understanding of travel requirements and visa procedures.',
                        'is_active' => true,
                        'sort_order' => 1,
                    ],
                    [
                        'icon' => 'SU',
                        'title_ar' => 'متابعة ودعم',
                        'title_en' => 'Follow-Up & Support',
                        'text_ar' => 'نساعدك في خطوات تجهيز المستندات وإجراءات التقديم.',
                        'text_en' => 'Guiding you through document preparation and application steps.',
                        'is_active' => true,
                        'sort_order' => 2,
                    ],
                    [
                        'icon' => 'SP',
                        'title_ar' => 'فريق متخصص',
                        'title_en' => 'Specialized Team',
                        'text_ar' => 'فريق يساعدك على فهم الخطوات المناسبة حسب وجهتك واحتياجاتك.',
                        'text_en' => 'A dedicated team helping you navigate options tailored to your destination.',
                        'is_active' => true,
                        'sort_order' => 3,
                    ],
                    [
                        'icon' => 'VL',
                        'title_ar' => 'خدمات متكاملة',
                        'title_en' => 'Integrated Services',
                        'text_ar' => 'من التأشيرة والطيران والفنادق إلى الرحلات السياحية وخدمات السفر المساندة.',
                        'text_en' => 'From visas, flights, and hotels to tours and travel support services.',
                        'is_active' => true,
                        'sort_order' => 4,
                    ],
                    [
                        'icon' => 'FO',
                        'title_ar' => 'اهتمام باحتياجات العميل',
                        'title_en' => 'Focus on Client Needs',
                        'text_ar' => 'نحاول نفهم احتياجك أولًا ثم نساعدك في اختيار الخدمة المناسبة.',
                        'text_en' => 'We prioritize understanding your needs before recommending the right service.',
                        'is_active' => true,
                        'sort_order' => 5,
                    ],
                    [
                        'icon' => 'BO',
                        'title_ar' => 'سهولة التواصل',
                        'title_en' => 'Easy Communication',
                        'text_ar' => 'يمكنك التواصل معنا للحصول على المعلومات والمساعدة في خطوات السفر.',
                        'text_en' => 'Accessible communication channels for quick information and assistance.',
                        'is_active' => true,
                        'sort_order' => 6,
                    ],
                ],
            ],
            'how_it_works' => [
                'enabled' => true,
                'eyebrow_ar' => 'طريقة عملنا',
                'eyebrow_en' => 'How We Work',
                'title_ar' => 'إزاي بنساعدك؟',
                'title_en' => 'How We Help You',
                'items' => [
                    [
                        'step_number' => '01',
                        'title_ar' => 'اختار الخدمة المناسبة',
                        'title_en' => 'Choose the Right Service',
                        'text_ar' => 'حدد احتياجك سواء تأشيرة أو رحلة أو طيران أو فندق أو أي خدمة سفر أخرى.',
                        'text_en' => 'Select your service whether visa, trip, flight, hotel, or travel support.',
                        'is_active' => true,
                        'sort_order' => 1,
                    ],
                    [
                        'step_number' => '02',
                        'title_ar' => 'شاركنا تفاصيل رحلتك',
                        'title_en' => 'Share Your Trip Details',
                        'text_ar' => 'أرسل لنا المعلومات الأساسية حتى نقدر نفهم احتياجك بشكل أفضل.',
                        'text_en' => 'Send us basic details so we can understand your exact needs.',
                        'is_active' => true,
                        'sort_order' => 2,
                    ],
                    [
                        'step_number' => '03',
                        'title_ar' => 'نوضح لك الخطوات المناسبة',
                        'title_en' => 'Get Clear Next Steps',
                        'text_ar' => 'نساعدك في معرفة المتطلبات والإجراءات اللازمة حسب الخدمة والوجهة.',
                        'text_en' => 'We outline the exact requirements and steps for your chosen service.',
                        'is_active' => true,
                        'sort_order' => 3,
                    ],
                    [
                        'step_number' => '04',
                        'title_ar' => 'استعد لرحلتك',
                        'title_en' => 'Get Ready for Your Journey',
                        'text_ar' => 'نساعدك في إكمال الإجراءات والاستعداد للسفر.',
                        'text_en' => 'We assist you in finalizing all arrangements so you are travel-ready.',
                        'is_active' => true,
                        'sort_order' => 4,
                    ],
                ],
            ],
            'mission' => [
                'enabled' => true,
                'eyebrow_ar' => 'هدفنا ورسالتنا',
                'eyebrow_en' => 'Our Goal',
                'title_ar' => 'هدفنا',
                'title_en' => 'Our Goal',
                'description_ar' => "هدفنا في Travel Wave هو جعل خدمات السفر أكثر وضوحًا وسهولة، وتقديم دعم احترافي يساعد العميل على اتخاذ القرار المناسب والاستعداد لرحلته بشكل أفضل.\n\nبنركز على فهم احتياجات كل عميل وتقديم الخدمة المناسبة له بدلًا من تقديم حل واحد للجميع.",
                'description_en' => "Our goal at Travel Wave is to make travel services clearer and simpler, providing professional support that helps clients make informed decisions and prepare better for their trips.\n\nWe focus on understanding each client's specific needs to deliver tailored solutions rather than one-size-fits-all services.",
            ],
            'cta' => [
                'enabled' => true,
                'eyebrow_ar' => 'ابدأ معنا',
                'eyebrow_en' => 'Start Your Trip',
                'title_ar' => 'جاهز تبدأ رحلتك؟',
                'title_en' => 'Ready to Start Your Journey?',
                'description_ar' => 'احكيلنا عن وجهتك واحتياجك، وفريق Travel Wave هيساعدك تعرف الخطوات المناسبة.',
                'description_en' => 'Tell us about your destination and requirements, and the Travel Wave team will guide you through the right steps.',
                'primary_button_text_ar' => 'ابدأ الآن',
                'primary_button_text_en' => 'Start Now',
                'primary_button_url' => '/contact',
                'secondary_button_text_ar' => 'تواصل معنا',
                'secondary_button_text_en' => 'Contact Us',
                'secondary_button_url' => '/contact#premium-contact-form',
            ],
        ];

        Page::updateOrCreate(
            ['key' => 'about'],
            [
                'key' => 'about',
                'title_ar' => 'من نحن',
                'title_en' => 'About Travel Wave',
                'slug' => 'about',
                'hero_badge_ar' => 'من نحن',
                'hero_badge_en' => 'About Us',
                'hero_title_ar' => 'من نحن',
                'hero_title_en' => 'About Travel Wave',
                'hero_subtitle_ar' => 'في Travel Wave بنساعدك تخطط لرحلتك بثقة، ونوفر لك خدمات السفر والتأشيرات من أول خطوة حتى الاستعداد للسفر.',
                'hero_subtitle_en' => 'We help you plan your journey with confidence, providing professional travel and visa services from the first step until you are ready to travel.',
                'hero_primary_cta_text_ar' => 'ابدأ الآن',
                'hero_primary_cta_text_en' => 'Start Now',
                'hero_primary_cta_url' => '/contact',
                'hero_secondary_cta_text_ar' => 'تواصل معنا',
                'hero_secondary_cta_text_en' => 'Contact Us',
                'hero_secondary_cta_url' => '/contact#premium-contact-form',
                'intro_title_ar' => 'من نحن؟',
                'intro_title_en' => 'Who We Are',
                'intro_body_ar' => 'Travel Wave شركة متخصصة في خدمات السفر والسياحة والتأشيرات، بنساعد عملاءنا على التخطيط لرحلاتهم وإنهاء الإجراءات المرتبطة بالسفر بطريقة منظمة واحترافية.',
                'intro_body_en' => 'Travel Wave is a specialized travel, tourism, and visa services agency helping clients plan trips professionally.',
                'sections' => $aboutSections,
                'meta_title_ar' => 'Travel Wave | خدمات السفر والتأشيرات والرحلات السياحية',
                'meta_title_en' => 'Travel Wave | Travel, Visas & Tourism Services',
                'meta_description_ar' => 'تعرف على Travel Wave وخدماتنا في التأشيرات، حجوزات الطيران والفنادق، الرحلات السياحية وتجهيز ملفات التأشيرات وخدمات السفر.',
                'meta_description_en' => 'Learn about Travel Wave and our visa services, flight and hotel bookings, tour packages, and travel support.',
                'is_active' => true,
            ]
        );
    }
}
